version: 2
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories: 
      - "/web"
      - "/web/server"
    schedule:
      interval: weekly
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - "/web"
      - "/backend"
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
