version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
    groups:
      gradle:
        patterns:
          - "*"

  - package-ecosystem: npm
    directories: 
      - "/web"
      - "/web/server"
    schedule:
      interval: weekly
    registries: "*"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - "/web"
      - "/backend"
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
