apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss-backend
  namespace: team-tolk
  labels:
    team: team-tolk
spec:
  image: { { image } }
  port: 8080
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: kviss
            envVarPrefix: DB
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  ingresses:
    - https://kviss-backend.dev.nav.no/
