apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: navhoot-backend
  namespace: team-tolk
  labels:
    team: team-tolk
spec:
  image: {{ image }}
  port: 8080
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: navhoot-db
  ingresses:
    - https://navhoot-backend.dev.nav.no/
  #image: ghcr.io/navikt/myapplication:417dcaa2c839b9da72e0189e2cfdd4e90e9cc6fd
  #       ^--- interpolated from the ${{ env.docker_image }} variable in the action