apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss-api
  namespace: team-tolk
  labels:
    team: team-tolk
  annotations:
    likerd.io/inject: "false"
spec:
  image: {{ image }}
  port: 8080
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: kviss-db
            envVarPrefix: DB
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  ingresses:
    - https://kviss-api.dev.nav.no/
    - https://kviss-api.dev.intern.nav.no/
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
  accessPolicy:
    inbound:
      rules:
        - application: kviss
        - application: kviss-vite-frontend
