apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss-api
  namespace: appsec
  labels:
    team: appsec
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
  resources:
    requests:
      cpu: 20m
      memory: 256Mi
    limits:
      memory: 512Mi
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        databases:
          - name: kviss-db
            envVarPrefix: DB
        tier: db-g1-small
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  accessPolicy:
    inbound:
      rules:
        - application: kviss
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
