apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss-api
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  image: "{{ image }}"
  port: 8080
  azure:
    application:
      enabled: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: kviss-db
            envVarPrefix: DB
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  accessPolicy:
    inbound:
      rules:
        - application: kviss