name: Automerge Dependabot PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@v1.2.2
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: '1'
