name: Deploy frontend
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - web/**
env:
  docker_image: ghcr.io/${{ github.repository }}-web:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # dep-submission
      id-token: write # nais docker-build-push
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # ratchet:actions/checkout@v2
      - name: Setup Node 20
        uses: actions/setup-node@25b062c917b0c75f8b47d8469aff6c94ffd89abb # ratchet:actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Yarn install and build client
        working-directory: web
        run: yarn install && yarn build
      - name: Yarn install and build server
        working-directory: web/server
        run: yarn install && yarn build
      - uses: nais/docker-build-push@3e3dd59e778ead7ba199dbfcde40350a178a2226 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: security-champion-admin
          push_image: true
          pull: true
          docker_context: web/
          dockerfile: web/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@b3ee57a58e6ffbc7dc0586f3781a41e807eda467 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: web/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
