name: Deploy frontend
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - web/**
env:
  docker_image: ghcr.io/${{ github.repository }}-web:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # dep-submission
      id-token: write # nais docker-build-push
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # ratchet:actions/checkout@v2
      - name: Setup Node 18
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # ratchet:actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Yarn install and build client
        working-directory: web
        run: yarn install && yarn build
      - name: Yarn install and build server
        working-directory: web/server
        run: yarn install && yarn build
      - uses: nais/docker-build-push@3257289fd8cb0018ce0bda55db86ee54c21669b1 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: security-champion-admin
          push_image: true
          pull: true
          docker_context: web/
          dockerfile: web/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@0bca2c7e607d30fd757a2a23fb7d07b3ff96d540 # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: web/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
