name: Build & deploy frontend
on:
  workflow_dispatch: # Allow manually triggered workflow run
  push:
    branches:
      - main
    paths:
      - web/**
permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # dep-submission
      id-token: write # nais docker-build-push
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # ratchet:actions/checkout@v2
      - name: Setup Node 20
        uses: actions/setup-node@25b062c917b0c75f8b47d8469aff6c94ffd89abb # ratchet:actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Yarn install and build client
        working-directory: web
        run: yarn install && yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn install and build server
        working-directory: web/server
        run: yarn install && yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - uses: nais/docker-build-push@099f6e6d0b4fa8899d03aae7dd274f87d4ff0651 # ratchet:nais/docker-build-push@v0
        id: docker-push
        with:
          team: security-champion-admin
          push_image: true
          pull: true
          docker_context: web/
          dockerfile: web/Dockerfile
          image_suffix: frontend
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: nais/deploy/actions/deploy@96e757fcdfbced4bb66b28b0cd6133006e71e47d # ratchet:nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: web/nais.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
