name: Deploy frontend

on:
  workflow_dispatch: # Allow manually triggered workflow run
    push:
      branches:
        - main

env:
  docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}
  CLUSTER: dev-gcp
  RESOURCE: web/nais.yaml

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ${{ env.docker_image }}

  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: web/nais.yaml
          VAR: image=${{ env.docker_image }}
