name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    uses: navikt/digestabot/.github/workflows/update-images.yml@main
    secrets: inherit
    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # for nais login and used to sign the commits using gitsign
    with:
      team: appsec
