apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss
  namespace: security-champion-admin
  labels:
    team: security-champion-admin
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://kviss.nav.no/
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /internal/isalive
    initialDelay: 10
  readiness:
    path: /internal/isready
    initialDelay: 10
  env:
    - name: API_URL
      value: http://kviss-api
    - name: APIE_SCOPE
      value: api://prod-gcp.security-champion-admin.kviss-api/.default
  accessPolicy:
    outbound:
      rules:
        - application: kviss-api
