apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://kviss.dev.intern.nav.no/
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /internal/isalive
    initialDelay: 10
  readiness:
    path: /internal/isready
    initialDelay: 10
  env:
    - name: API_URL
      value: http://kviss-api
  accessPolicy:
    outbound:
      rules:
        - application: kviss-api
