apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kviss
  namespace: team-tolk
  labels:
    team: team-tolk
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - https://kviss.dev.intern.nav.no/
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  template:
    metadata:
      labels:
        app: kviss
      annotations:
        linkerd.io/inject: "false"
  accessPolicy:
    outbound:
      rules:
        - application: kviss-api
